package com.spun.util.sql;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

public class MockConnection implements Connection
{
  public Statement createStatement()
  {
    return null;
  }
  public PreparedStatement prepareStatement(String sql)
  {
    return null;
  }
  public CallableStatement prepareCall(String sql)
  {
    return null;
  }
  public String nativeSQL(String sql)
  {
    return null;
  }
  public void setAutoCommit(boolean autoCommit)
  {
  }
  public boolean getAutoCommit()
  {
    return false;
  }
  public void commit()
  {
  }
  public void rollback()
  {
  }
  public void close()
  {
  }
  public boolean isClosed()
  {
    return false;
  }
  public DatabaseMetaData getMetaData()
  {
    return new MockDatabaseMetaData();
  }
  public void setReadOnly(boolean readOnly)
  {
  }
  public boolean isReadOnly()
  {
    return false;
  }
  public void setCatalog(String catalog)
  {
  }
  public String getCatalog()
  {
    return null;
  }
  public void setTransactionIsolation(int level)
  {
  }
  public int getTransactionIsolation()
  {
    return 0;
  }
  public SQLWarning getWarnings()
  {
    return null;
  }
  public void clearWarnings()
  {
  }
  public Statement createStatement(int resultSetType, int resultSetConcurrency)
  {
    return null;
  }
  public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
  {
    return null;
  }
  public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency)
  {
    return null;
  }
  public Map<String, Class<?>> getTypeMap()
  {
    return null;
  }
  public void setTypeMap(Map<String, Class<?>> arg0)
  {
  }
  public void setHoldability(int holdability)
  {
  }
  public int getHoldability()
  {
    return 0;
  }
  public Savepoint setSavepoint()
  {
    return null;
  }
  public Savepoint setSavepoint(String name)
  {
    return null;
  }
  public void rollback(Savepoint savepoint)
  {
  }
  public void releaseSavepoint(Savepoint savepoint)
  {
  }
  public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability)
  {
    return null;
  }
  public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency,
      int resultSetHoldability)
  {
    return null;
  }
  public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency,
      int resultSetHoldability)
  {
    return null;
  }
  public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys)
  {
    return null;
  }
  public PreparedStatement prepareStatement(String sql, int[] columnIndexes)
  {
    return null;
  }
  public PreparedStatement prepareStatement(String sql, String[] columnNames)
  {
    return null;
  }
  public Array createArrayOf(String arg0, Object[] arg1)
  {
    return null;
  }
  public Blob createBlob()
  {
    return null;
  }
  public Clob createClob()
  {
    return null;
  }
  public NClob createNClob()
  {
    return null;
  }
  public SQLXML createSQLXML()
  {
    return null;
  }
  public Struct createStruct(String arg0, Object[] arg1)
  {
    return null;
  }
  public Properties getClientInfo()
  {
    return null;
  }
  public String getClientInfo(String arg0)
  {
    return null;
  }
  public boolean isValid(int arg0)
  {
    return false;
  }
  public void setClientInfo(Properties arg0) throws SQLClientInfoException
  {
  }
  public void setClientInfo(String arg0, String arg1) throws SQLClientInfoException
  {
  }
  public boolean isWrapperFor(Class<?> arg0)
  {
    return false;
  }
  public <T> T unwrap(Class<T> arg0)
  {
    return null;
  }
  public void abort(Executor arg0)
  {
  }
  public int getNetworkTimeout()
  {
    return 0;
  }
  public String getSchema()
  {
    return null;
  }
  public void setNetworkTimeout(Executor arg0, int arg1)
  {
  }
  public void setSchema(String arg0)
  {
  }
}
