version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    groups:
      junit:
        patterns:
          - "org.junit.*"
      jackson:
        patterns:
          - "com.fasterxml.*"
    commit-message:
      prefix: "- r "
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ". e "
