package com.spun.util;

public class NameUtils
{
 	/***********************************************************************/
	public static String getRandomFirstName() 
	{
		String[] names = new String[]{"James",
			"John",
			"Robert",
			"Michael",
			"William",
			"David",
			"Richard",
			"Charles",
			"Joseph",
			"Thomas",
			"Christopher",
			"Daniel",
			"Paul",
			"Mark",
			"Donald",
			"George",
			"Kenneth",
			"Steven",
			"Edward",
			"Brian",
			"Ronald",
			"Anthony",
			"Kevin",
			"Jason",
			"Matthew",
			"Gary",
			"Timothy",
			"Jose",
			"Larry",
			"Jeffrey",
			"Frank",
			"Scott",
			"Eric",
			"Stephen",
			"Andrew",
			"Raymond",
			"Gregory",
			"Joshua",
			"Jerry",
			"Dennis",
			"Walter",
			"Patrick",
			"Peter",
			"Harold",
			"Douglas",
			"Henry",
			"Carl",
			"Arthur",
			"Ryan",
			"Roger"                              };
		return names[NumberUtils.RANDOM.nextInt(names.length)];
	}
	
	/***********************************************************************/
	public static String getRandomLastName() 
	{
		String[] names  = new String[]{"Smith",
			"Johnson",
			"Williams",
			"Jones",
			"Brown",
			"Davis",
			"Miller",
			"Wilson",
			"Moore",
			"Taylor",
			"Anderson",
			"Thomas",
			"Jackson",
			"White",
			"Harris",
			"Martin",
			"Thompson",
			"Garcia",
			"Martinez",
			"Robinson",
			"Clark",
			"Rodriguez",
			"Lewis",
			"Lee",
			"Walker",
			"Hall",
			"Allen",
			"Young",
			"Hernandez",
			"King",
			"Wright",
			"Lopez",
			"Hill",
			"Scott",
			"Green",
			"Adams",
			"Baker",
			"Gonzalez",
			"Nelson",
			"Carter",
			"Mitchell",
			"Perez",
			"Roberts",
			"Turner",
			"Phillips",
			"Campbell",
			"Parker",
			"Evans",
			"Edwards",
			"Collins"                            };    
		return names[NumberUtils.RANDOM.nextInt(names.length)];
	}
	
	
	/************************************************************************/
	/************************************************************************/
}