name: Format and Update markdown snippets

on:
  push:
    branches: ['master']
  workflow_dispatch:

# Cancel existing executions when new commits are pushed onto the branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-markdown-snippets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v2
      - run: ./format_code.sh
      - run: ./run_markdown_templates.sh
      - name: Git Commit and Push
        uses: github-actions-x/commit@v2.9
        with:
          commit-message: ". d reformatted code and updated markdown snippets"
          rebase: 'true'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          name: github actions
          email: actions@github.com
    
